### ISSUE TITLE
Redemption_Process Error - Insufficient fee?

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/asset-mapping#19]
Exception: Error in RPC call: {'code': -26, 'message': '66: insufficient fee'}

Log-

Redemption transaction processing
Load the mapping object - connecting to S3
    Timestamp: 1561407750.3378088 (Mon Jun 24 21:22:30 2019)
    Signatures verified
 
Load the redeem list object - rassets.json
 
Connecting to Ocean client
 
Token ratio = 0.09998841296 at block 6095
 
Enter redeemed asset reference: 100041-2019-DAN
 
Asset mass: 400.000
Required tokens: 4000.46353549
 
Read in redemption (freeze) transaction
 
    Redemption transaction valid
 
    Redemption transaction has sufficient tokens
 
ALL REDEMPTION CHECKS PASSED
Locking asset in redeem list
Add redemption transaction addresses to the freezelist
 
 
Policy asset UTXOs found: 88
Sent 2 freezelist txs: 
    c6d3fdc9150388c61b1c030b1cd3154a34dd4f9df48bc4efe54494718f9f704e
    6656d3b1bfd8e256e9c96247156cef973f1b842e0b17d52a06cc2d04096f977d
 
Pause for on-chain confirmation
.................................. 
    Check policy transactins confirmed
Pause for on-chain confirmation
.................................. 
    Check policy transactins confirmed
Submit redemption transaction to network
Traceback (most recent call last):
  File "redeem_process.py", line 227, in <module>
    rtxid = ocean.call('sendrawtransaction',rtx["hex"])
  File "/usr/local/lib/python3.7/site-packages/amap-0.1-py3.7.egg/amap/rpchost.py", line 31, in call
Exception: Error in RPC call: {'code': -26, 'message': '66: insufficient fee'}
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by cryptopoly** [comment]
Fixed @tomt1664
