### ISSUE TITLE
Negative blockheight

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/asset-mapping#9]
Found record in coins with negative blockheight.

Right clicked & details then crash!

Screenshot
https://www.dropbox.com/s/3uouw5xvhk3prn0/Screenshot%202019-06-07%2011.35.15.png?dl=0

Last login: Fri Jun  7 09:14:36 on ttys002
cryptopolys-MacBook-Pro:~ cryptopoly$ cd cb-client-wallet./run_electrum --testnet
-bash: cd: cb-client-wallet./run_electrum: No such file or directory
cryptopolys-MacBook-Pro:~ cryptopoly$ cd cb-client-wallet ./run_electrum --testnet
cryptopolys-MacBook-Pro:cb-client-wallet cryptopoly$ ./run_electrum --testnet
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/utxo_list.py", line 79, in <lambda>
    menu.addAction(_("Details"), lambda: self.parent.show_transaction(tx))
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 810, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 57, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 163, in __init__
    self.update()
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 256, in update
    fee = self.tx.get_fee()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1153, in get_fee
    return self.input_value() - self.output_value()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Abort trap: 6
cryptopolys-Mac

**Comment by cryptopoly** [comment]
Also crashed on double clicking 'saved' transaction [redeem, sign tx, save transaction]

Saved file locally, try and double click on the record
https://www.dropbox.com/s/r13a6ixbufvz6c9/Screenshot%202019-06-07%2011.38.17.png?dl=0

cryptopolys-MacBook-Pro:cb-client-wallet cryptopoly$ ./run_electrum --testnet
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/history_list.py", line 302, in on_doubleclick
    self.parent.show_transaction(tx)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 810, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 57, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 163, in __init__
    self.update()
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 256, in update
    fee = self.tx.get_fee()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1153, in get_fee
    return self.input_value() - self.output_value()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Abort trap: 6
cryptopolys-MacBook-Pro:cb-client-wallet cryptopoly$ ./run_electrum --testnet
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa

**Comment by tomt1664** [comment]
Negative blockheight is due to a locally saved non-confirmed transaction.
